#!/bin/sh
# Auto-generate schema and stage it if changed
npm run generate-schema

# If the schema file changed, stage it
git diff --quiet -- src/schema/edict-ast.schema.json || git add src/schema/edict-ast.schema.json
